package MyController;

import AutoGeneratedValues.CurrentDateGenerator;
import AutoGeneratedValues.TransactionIdGenerator;
import Entity.transaction;
import Services.transactionprop;

import java.sql.Date;
import java.text.SimpleDateFormat;

public class transactionControl {

    public static boolean saveTransaction(long accno, long tamount, String ttype){
        transaction tc = new transaction();
        tc.setAccno(accno);
        tc.setTamount(tamount);
        tc.setTtype(ttype);
        String tid = TransactionIdGenerator.generateTransactionId(8);
//        Date date;
//        date = Date.valueOf(CurrentDateGenerator.generateDate());
        String currentDate = CurrentDateGenerator.getCurrentDate();
        // To print the date in yyyy/MM/dd format
      //  SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
        //System.out.println(formatter.format(currentDate));
        tc.setTdate(Date.valueOf(currentDate));
       // String id = TransactionIdGenerator.generateTransactionId(5);
        tc.setTid(tid);
        if(transactionprop.saveTransaction(tc)){
            return true;
        }
        return false;
    }

    public static void getTransactionById(String tid){
        transactionprop.fetchTransaction(tid);
    }

    public static void get10Transaction(long accno){
        transactionprop.fetch10Transaction(accno);
    }

}
