package AutoGeneratedValues;

import java.security.SecureRandom;

public class AccountNumGenerator {
    private static final String CHARACTERS = "0123456789";

    // Secure random number generator
    private static SecureRandom random = new SecureRandom();

    public static String generateAccountNum(int length) {
        StringBuilder accountNum = new StringBuilder(length);

        // Generate password by randomly picking characters from CHARACTERS
        for (int i = 0; i < length; i++) {
            int randomIndex = random.nextInt(CHARACTERS.length());
            accountNum.append(CHARACTERS.charAt(randomIndex));
        }

        return accountNum.toString();
    }
}
