package AutoGeneratedValues;



import java.text.SimpleDateFormat;
import java.util.Date;

public class CurrentDateGenerator {
//    public static Date generateDate() {
////        SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
////        Date date = new Date();
////        String datetime =  formatter.format(date);
////        return datetime;
//        // Get the current date and time
//        long millis = System.currentTimeMillis();
//        // Create a java.sql.Date object from the current time in milliseconds
//        return new Date(millis);
//    }

        public static String returnCurrentDate(String[] args) {
            String currentDate = getCurrentDate();
            //System.out.println("Current Date: " + currentDate);
            return currentDate;
        }

        public static String getCurrentDate() {
            // Create a SimpleDateFormat instance with the desired date format
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            // Get the current date
            Date date = new Date();

            // Format the current date as a string
            return sdf.format(date);
        }


}
