package AutoGeneratedValues;

import java.security.SecureRandom;

public class TransactionIdGenerator {
    private static final String CHARACTERS = "DW0123456789";

    // Secure random number generator
    private static SecureRandom random = new SecureRandom();

    public static String generateTransactionId(int length) {
        StringBuilder transactionId = new StringBuilder(length);

        // Generate password by randomly picking characters from CHARACTERS
        for (int i = 0; i < length; i++) {
            int randomIndex = random.nextInt(CHARACTERS.length());
            transactionId.append(CHARACTERS.charAt(randomIndex));
        }

        return transactionId.toString();
    }

}
